os.loadAPI("FireCast/APIs/revplus")
term.setBackgroundColour(colours.orange)
term.setTextColour(colours.white)
term.clear()
term.setCursorPos(1,5)
revplus.centerSlow("Welcome to FireCast.")
sleep(0.5)
term.setCursorPos(1,6)
revplus.centerSlow("The Ultimate Innovation.")
sleep(2.5)
shell.run("FireCast/Menu")
